### ISSUE TITLE
Unnecessary RPC call to server when TextArea is disabled on initial render

### ISSUE THREAD

**Issue by jounik** [henrikerola/ExpandingTextArea#5]
If you set the TextArea disabled before the initial paint, the client sends an unnecessary RPC call to the server which causes a warning to be printed on the console.

**Comment by jounik** [comment]
Any thoughts when you might release 1.1.0? I could update Sampler to use that then immediately.

**Comment by henrikerola** [comment]
Took more time as planned but I just released version 1.1.0 that contains the fix.
