### ISSUE TITLE
Addon stylesheet not found

### ISSUE THREAD

**Issue by moberwasserlechner** [henrikerola/ExpandingTextArea#7]
Hi,

after including this addon I get this log message on first application access.

```
2015-10-24 23:47:13.711 INFO  com.vaadin.server.VaadinServlet - Requested resource [/VAADIN/widgetsets/MyWidgetset/expandingtextarea/expandingtextarea.css] not found from filesystem or through class loader. Add widgetset and/or theme JAR to your classpath or add files to WebContent/VAADIN folder.
```

As a workaround I manually created the folder and copy the css from the jar to the required file.

I think - but I'm not sure - if you move the "expandingtextarea/expandingtextarea.css" in a new folder "public/expandingtextarea/expandingtextarea.css" no further manual action would be required. The folder "public" must be in the same folder as "ExpandingtextareaWidgetset.gwt.xml".

Btw. I'm using Vaadin 7.5.8 and build or compile the widget set with Gradle (https://github.com/johndevs/gradle-vaadin-plugin)

Thanks & BR,
Michael

**Comment by henrikerola** [comment]
Thanks for reporting this, this was broken due to migrating project's build to sbt (and me ignoring warnings about the missing file :)
